# Generated by Django 5.2.6 on 2025-09-04 09:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Criminal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('alias', models.CharField(blank=True, max_length=100, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('U', 'Unknown')], default='U', max_length=1)),
                ('threat_level', models.CharField(choices=[('LOW', 'Low Threat'), ('MEDIUM', 'Medium Threat'), ('HIGH', 'High Threat'), ('EXTREME', 'Extreme Threat')], default='LOW', max_length=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('physical_characteristics', models.TextField(blank=True, null=True)),
                ('is_incarcerated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PoliceOfficer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_number', models.CharField(max_length=20, unique=True)),
                ('rank', models.CharField(choices=[('CONSTABLE', 'Constable'), ('SERGEANT', 'Sergeant'), ('INSPECTOR', 'Inspector'), ('CAPTAIN', 'Captain')], max_length=20)),
                ('station', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Crime',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('crime_type', models.CharField(choices=[('THEFT', 'Theft'), ('ASSAULT', 'Assault'), ('BURGLARY', 'Burglary'), ('ROBBERY', 'Robbery'), ('DRUGS', 'Drug Offense'), ('FRAUD', 'Fraud'), ('HOMICIDE', 'Homicide'), ('OTHER', 'Other')], max_length=20)),
                ('description', models.TextField()),
                ('date_committed', models.DateField()),
                ('location', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('OPEN', 'Open Investigation'), ('CLOSED', 'Case Closed'), ('CONVICTED', 'Convicted')], default='OPEN', max_length=20)),
                ('criminal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crimes', to='police_profiling.criminal')),
                ('arresting_officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='police_profiling.policeofficer')),
            ],
        ),
    ]
