# Generated by Django 5.2.6 on 2025-09-04 22:03

import django.db.models.deletion
import police_profiling.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('police_profiling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='criminal',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=police_profiling.models.criminal_image_path),
        ),
        migrations.CreateModel(
            name='CriminalDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('ARREST_REPORT', 'Arrest Report'), ('COURT_DOCUMENT', 'Court Document'), ('MEDICAL_REPORT', 'Medical Report'), ('FINGERPRINT', 'Fingerprint Record'), ('WARRANT', 'Warrant'), ('OTHER', 'Other Document')], max_length=20)),
                ('file', models.FileField(upload_to=police_profiling.models.criminal_documents_path)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
                ('criminal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='police_profiling.criminal')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='police_profiling.policeofficer')),
            ],
        ),
        migrations.CreateModel(
            name='CriminalEvidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('evidence_type', models.CharField(choices=[('PHOTO', 'Photograph'), ('VIDEO', 'Video Recording'), ('AUDIO', 'Audio Recording'), ('DOCUMENT', 'Document'), ('WEAPON', 'Weapon'), ('OTHER', 'Other Evidence')], max_length=20)),
                ('file', models.FileField(upload_to=police_profiling.models.criminal_evidence_path)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_collected', models.DateField(auto_now_add=True)),
                ('collected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='police_profiling.policeofficer')),
                ('criminal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='police_profiling.criminal')),
            ],
        ),
    ]
