# Generated by Django 5.1.2 on 2025-10-06 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('police_profiling', '0002_criminal_profile_picture_criminaldocument_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policeofficer',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
