# Generated by Django 5.1.2 on 2025-10-21 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('police_profiling', '0003_alter_policeofficer_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='criminal',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='criminal',
            name='alcohol_use_history',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='criminal',
            name='build',
            field=models.CharField(blank=True, choices=[('SLENDER', 'Slender'), ('AVERAGE', 'Average'), ('ATHLETIC', 'Athletic'), ('HEAVYSET', 'Heavyset'), ('MUSCULAR', 'Muscular'), ('STOCKY', 'Stocky')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='criminal',
            name='complexion',
            field=models.CharField(blank=True, choices=[('FAIR', 'Fair'), ('LIGHT', 'Light'), ('MEDIUM', 'Medium'), ('OLIVE', 'Olive'), ('DARK', 'Dark'), ('DARK_BROWN', 'Dark Brown'), ('BLACK', 'Black')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='criminal',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_criminals', to='police_profiling.policeofficer'),
        ),
        migrations.AddField(
            model_name='criminal',
            name='criminal_history',
            field=models.TextField(blank=True, help_text='Summary of criminal history', null=True),
        ),
        migrations.AddField(
            model_name='criminal',
            name='current_facility',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='criminal',
            name='distinguishing_marks',
            field=models.TextField(blank=True, help_text='Tattoos, scars, birthmarks, etc.', null=True),
        ),
        migrations.AddField(
            model_name='criminal',
            name='dna_profile',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='criminal',
            name='drug_use_history',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='criminal',
            name='education_level',
            field=models.CharField(choices=[('NONE', 'No Formal Education'), ('PRIMARY', 'Primary School'), ('SECONDARY', 'Secondary School'), ('HIGH_SCHOOL', 'High School'), ('DIPLOMA', 'Diploma/Certificate'), ('BACHELORS', "Bachelor's Degree"), ('MASTERS', "Master's Degree"), ('DOCTORATE', 'Doctorate'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=20),
        ),
        migrations.AddField(
            model_name='criminal',
            name='email_addresses',
            field=models.JSONField(blank=True, default=list, help_text='List of known email addresses'),
        ),
        migrations.AddField(
            model_name='criminal',
            name='employment_status',
            field=models.CharField(choices=[('EMPLOYED', 'Employed'), ('UNEMPLOYED', 'Unemployed'), ('SELF_EMPLOYED', 'Self-Employed'), ('STUDENT', 'Student'), ('RETIRED', 'Retired'), ('DISABLED', 'Disabled'), ('INCARCERATED', 'Incarcerated'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=20),
        ),
        migrations.AddField(
            model_name='criminal',
            name='escape_risk',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='criminal',
            name='expected_release_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='criminal',
            name='eye_color',
            field=models.CharField(blank=True, choices=[('BROWN', 'Brown'), ('BLUE', 'Blue'), ('GREEN', 'Green'), ('HAZEL', 'Hazel'), ('GRAY', 'Gray'), ('BLACK', 'Black'), ('OTHER', 'Other')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='criminal',
            name='fingerprint_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='criminal',
            name='gang_affiliations',
            field=models.TextField(blank=True, help_text='Gang memberships or affiliations', null=True),
        ),
        migrations.AddField(
            model_name='criminal',
            name='hair_color',
            field=models.CharField(blank=True, choices=[('BLACK', 'Black'), ('BROWN', 'Brown'), ('BLONDE', 'Blonde'), ('RED', 'Red'), ('GRAY', 'Gray'), ('WHITE', 'White'), ('BALD', 'Bald'), ('OTHER', 'Other')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='criminal',
            name='height',
            field=models.CharField(blank=True, help_text='Height in cm or feet/inches', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='criminal',
            name='incarceration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='criminal',
            name='known_associates',
            field=models.TextField(blank=True, help_text='Names and relationships of known associates', null=True),
        ),
        migrations.AddField(
            model_name='criminal',
            name='last_known_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='criminal',
            name='last_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_criminals', to='police_profiling.policeofficer'),
        ),
        migrations.AddField(
            model_name='criminal',
            name='marital_status',
            field=models.CharField(choices=[('SINGLE', 'Single'), ('MARRIED', 'Married'), ('DIVORCED', 'Divorced'), ('WIDOWED', 'Widowed'), ('SEPARATED', 'Separated'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=20),
        ),
        migrations.AddField(
            model_name='criminal',
            name='medical_conditions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='criminal',
            name='modus_operandi',
            field=models.TextField(blank=True, help_text="Criminal's methods and patterns", null=True),
        ),
        migrations.AddField(
            model_name='criminal',
            name='nationality',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='criminal',
            name='occupation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='criminal',
            name='phone_numbers',
            field=models.JSONField(blank=True, default=list, help_text='List of known phone numbers'),
        ),
        migrations.AddField(
            model_name='criminal',
            name='place_of_birth',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='criminal',
            name='psychological_profile',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='criminal',
            name='violent_offender',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='criminal',
            name='weapons_preference',
            field=models.TextField(blank=True, help_text='Preferred weapons or tools', null=True),
        ),
        migrations.AddField(
            model_name='criminal',
            name='weight',
            field=models.CharField(blank=True, help_text='Weight in kg or lbs', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='policeofficer',
            name='rank',
            field=models.CharField(choices=[('CONSTABLE', 'Constable'), ('SERGEANT', 'Sergeant'), ('INSPECTOR', 'Inspector'), ('COMMISSIONER', 'Commissioner')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='criminal',
            index=models.Index(fields=['last_name', 'first_name'], name='police_prof_last_na_fa2d14_idx'),
        ),
        migrations.AddIndex(
            model_name='criminal',
            index=models.Index(fields=['threat_level'], name='police_prof_threat__f778e1_idx'),
        ),
        migrations.AddIndex(
            model_name='criminal',
            index=models.Index(fields=['is_incarcerated'], name='police_prof_is_inca_ca4e2e_idx'),
        ),
        migrations.AddIndex(
            model_name='criminal',
            index=models.Index(fields=['created_at'], name='police_prof_created_c91943_idx'),
        ),
    ]
